<?php
	define("R5ENTER", "You descend the ladder through the passage way. As you descend you notice that the air is getting cooler and has a thick mildew smell. You wished you had brought a warmer set of clothes with you. You also wondered why you were doing this anyway. I mean who knows who or what could be down here. Oh well, you say! Throw caution to the wind!<br /><br />You step off the ladder onto a damp stone floor. There is a torch on each wall of the room giving the room ample light. The ladder from which you descended is in the middle of the room. There are four doors leading to the NORTH, EAST, SOUTH, and WEST.<br /><br />You notice two buttons on the floor; one is green and the other is red.");
	define("R5LOOK", "This room is practically empty. There is a ladder, a red button, a green button, and four exits. There is a torch on each wall. You also notice a soaked piece of paper on the ground.");
	define("R5PAPERLOOK", "The paper looks like it was torn out of a spiral notebook. It is wet from lying on the damp ground. Although the water has washed away some of the ink, you can still make out that someone wrote 'Conference Call today: 641-715-3900, passcode 906334#'.");
	define("GREENLOOK", "It's a round green button upon which is written the word 'Start' in white letters.");
	define("WHICHBUTTON", "Yes. I see. It's a button. Nice. Mmm Hmm. Um. As there are two buttons, each having a distinct color identifier, perhaps we could be a little bit more specific? Mmkay? Great.");
	define("FAILEDBUTTON", "You press the green button. It clicks and before you have time to move your hand a metal trap closes around your hand. You scream in pain, but no one can hear you. Or so you thought. A gust of wind blows through the room, extinguishing the torches. It's a good thing you have your flashlight!<BR /><BR />Wait, I forgot to tell you this. Well, now it's just awkward but...<BR /><BR />As the metal trap closed on your hand you dropped your flashlight and it rolled into another room. So yeah. Sorry.");
	define("REDLOOK", "It's a round red button upon which is written the word 'Reset' in white letters.");
	define("REDPUSH", "You push the red button. You hear gears turn and click. Something must have happened.");
	define("R5HINT", "After looking closer at the paper on the ground you also see a word, that has had some of the letters washed away, that reads 'm ni od m'.");
	define("PAPERTAKE", "Gross! You'd really want to pick up a soaked piece of paper? Really? And where would you put that huh? In your pocket? Great idea there! ... I meant, you can't take that. Silly autocorrect.");
?>